# Generated by Django 5.0.1 on 2024-01-27 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_feature_product_collection_featured_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='last_updated',
            new_name='last_update',
        ),
    ]
